version: "3"
services:
    gestal_api:
        container_name: gestal_api
        build:
            context: ./api
            dockerfile: Dockerfile
        image: damisaez/gestal_api
        ports:
            - "8084:8084"
        networks:
            - app-network
        depends_on:
            - mysql


    gestal_web:
        container_name: gestal_web
        build:
            context: ./web
            dockerfile: Dockerfile
        image: damisaez/gestal_web
        ports:
            - "8888:8888"
        networks:
            - app-network
        depends_on:
            - mysql

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'gestal'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'sa'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'sa'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: 'localhost'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local