version: "3"
services:
    gestal_api:
        container_name: gestal_api
        build:
            context: ./api
            dockerfile: Dockerfile
        image: damisaez/gestal_api
        ports:
            - "8084:8084"
        networks:
            - app-network
        depends_on:
            - gestal_db


    gestal_web:
        container_name: gestal_web
        build:
            context: ./web
            dockerfile: Dockerfile
        image: damisaez/gestal_web
        ports:
            - "8888:8888"
        networks:
            - app-network
        depends_on:
            - gestal_db

    gestal_db:
        image: mysql:5.6
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestal
            MYSQL_USER: sa
            MYSQL_PASSWORD: sa
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local